config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  root 'tweets#index'
  resources :tweets do
    collection do
      get 'search'
    end
    resources :messages, only: :create
  end

  resources :tags do
    get 'tweets', to: 'tweets#tag_search'
  end

  resources :users, only: :show do
    resources :five_km_records,  only: [:create, :update, :destroy]
    resources :ten_km_records,  only: [:create, :update, :destroy]
    resources :half_records,  only: [:create, :update, :destroy]
    resources :full_records,  only: [:create, :update, :destroy]
    resources :vdots,  only: [:index]
  end

  resources :follow_relationships, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
  resources :records,  only: [:new, :edit]
  resources :vdots,  only: [:index]
  post '/tweets/:tweet_id/likes' => 'likes#create'
  delete '/tweets/:tweet_id/likes' => 'likes#destroy'
  mount ActionCable.server => '/cable'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # ----- アソシエーション ----------------------------------------------
  has_many   :messages, dependent: :destroy
  has_many   :likes, dependent: :destroy
  has_many   :liked_users, through: :likes, source: :user
  has_many   :tag_tweets, dependent: :destroy
  has_many   :tags, through: :tag_tweets
  has_many   :notifications, dependent: :destroy
  belongs_to :user


  # ----- Gem関連 -----------------------------------------------------
  mount_uploader   :place_image, ImageUploader
  geocoded_by      :address
  after_validation :geocode, if: :address_changed?


  # -----バリデーション ------------------------------------------------
  with_options presence: true do
    validates :place_name,     null: false, length: { maximum: 16 }
    validates :place_image,    null: false
    validates :content,        null: false,   length: { maximum: 100 }
    validates :address,        null: false,   length: { maximum: 30 }
    validates :user
    validates :level
  end


  # ----- メソッド -----------------------------------------------------
  # 検索対象のカラムを設定。入力無しなら全て表示
  def self.search(search)
    if search != ''
      Tweet
        .where('place_name LIKE(?)', "%#{search}%")
        .or(Tweet.where('address LIKE(?)', "%#{search}%"))
        .or(Tweet.where('content LIKE(?)', "%#{search}%"))
    else
      Tweet.all
    end
  end

  # タグを保存する処理
  def save_tags(save_tweet_tags)
    current_tags = tags.pluck(:name) unless tags.nil?
    # 新・古タグをそれぞれ取得
    old_tags = current_tags - save_tweet_tags
    new_tags = save_tweet_tags - current_tags

    # 古いタグの削除
    old_tags.each do |old_name|
      tags.delete Tag.find_by(name: old_name)
    end

    # 新しいタグの保存
    new_tags.each do |new_name|
      tweet_tag = Tag.find_or_create_by(name: new_name)
      tags << tweet_tag
    end
  end

  # いいね・コメント数の取得
  def get_length
    @likes = likes.length
    @messages = messages.length
  end

  # いいねの通知作成
  def create_notification_like!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and tweet_id = ? and action = ? ',
                               current_user.id, user_id, id, 'like'])
    # 通知がすでに作成されていないか確認（同じ投稿へ通知が何度も来ないように）
    if temp.blank?
      notification = current_user.active_notifications.new(
        tweet_id: id,
        visited_id: user_id,
        action: 'like'
      )

      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  # コメントの通知作成
  def create_notification_message!(current_user, message_id)
    def save_notification_message!(current_user, message_id, visited_id)
      notification = current_user.active_notifications.new(
        tweet_id: id,
        message_id: message_id,
        visited_id: visited_id,
        action: 'message'
      )
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
   save_notification_message!(current_user, message_id, user_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # 未ログイン者の制限
  before_action :authenticate_user!, except: [:index, :show, :search, :tag_search]

  # ログイン者に紐づくコース投稿の中から、idが（params[:id]）のものを探す
  before_action :set_current_tweet, only: [:destroy, :edit, :update]

  # 各ランニングコース（人気・初心者向け・経験者向け）を取得
  before_action :get_recommended_tweets, only: :index

  # ビューに表示するタグを取得（最大18個）
  before_action :get_tags, only: [:index, :search, :tag_search]

  def index
    # コースを全て取得。コースが8つでページネーション
    @tweets = Tweet.includes([:user, :likes]).page(params[:page]).per(8).order('created_at DESC')
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)

    # タグを作成（ , で複数作成可能）
    tag_list = params[:tweet][:tag_ids].split(',')
    if @tweet.save
      @tweet.save_tags(tag_list)
      redirect_to root_path, notice: '投稿しました！'
    else
      render :new
    end
  end

  def show
    @tweet = Tweet.find(params[:id])

    # 選択したコースへのコメントを取得
    @tweet_messages = @tweet.messages.includes(:user).order('created_at DESC')

    # 他のコース（関連コース的な）として7つ表示
    @random = Tweet.order('RAND()').limit(7)

    # 選択したコースに付与されているタグを取得
    @tweet_tags = @tweet.tags
  end

  def destroy
    if @tweet.destroy
      redirect_to root_path, notice: '投稿を削除しました！'
    else
      render :show
    end
  end

  def edit
    # 選択したコースに付与されているタグを取得
    @tag_list = @tweet.tags.pluck(:name).join(',')
  end

  def update
    # 選択したコースに付与されているタグを取得
    tag_list = params[:tweet][:tag_ids].split(',')
    if @tweet.update(tweet_params)
      @tweet.save_tags(tag_list)
      redirect_to root_path, notice: '投稿を編集しました！'
    else
      render :edit
    end
  end

  # 検索ワードを含むコースを全て取得。コースが8つでページネーション
  # ※検索対象のカラムはtweetモデルのメソッドに設定してある
  def search
    @tweets = Tweet.search(params[:keyword]).includes([:user, :messages, :likes]).page(params[:page]).per(8).order('created_at DESC')
  end

  # 選択したタグを含むコースを全て取得。コースが8つでページネーション
  def tag_search
    @tag = Tag.find(params[:tag_id])
    @tweets = @tag.tweets.includes([:user, :messages, :likes]).page(params[:page]).per(8).order('created_at DESC')
  end

  private

  # ログイン者に紐づくコース投稿の中から、idが（params[:id]）のものを探す
  def set_current_tweet
    @tweet = current_user.tweets.find(params[:id])
  end

  # 外部入力を許可したカラム
  def tweet_params
    params.require(:tweet).permit(
      :content, :address, :longitude, :latitude, :place_name, :place_image, :level
    )
  end

  # 各ランニングコース（人気・初心者向け・経験者向け）を取得
  def get_recommended_tweets
    # いいねが最も多い順に、投稿を4つ取得
    tweets_ranking_sort = Tweet.includes([:user, :likes, :messages]).sort { |a, b| b.liked_users.count <=> a.liked_users.count}
    tweets_ranking = tweets_ranking_sort[0..3]

    # 初心者向けのコースをランダムに4つ取得
    tweets_beginner = Tweet.where(level: 1).order('RAND()').limit(4)

    # 経験者向けのコースをランダムに4つ取得
    tweets_senior = Tweet.where(level: 2).order('RAND()').limit(4)

    # 上記3つを配列にまとめる
    # ※ビューでeachメソッドを使うため
    @recommended_tweets = [tweets_ranking, tweets_beginner, tweets_senior]
  end

  # ビューに表示するタグを取得（最大18個）
  def get_tags
    @tag_lists = Tag.all.order('RAND()').limit(18)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
<div class="forms-container">

  <div class="titles mb-5">ランニングコースを編集</div>

  <div class="d-flex justify-content-center">
    <div class="forms-content">

      <%= form_with(model: @tweet, local: true) do |f| %>

        <%= render 'render/error_messages', model: f.object %>

        <div class="m-3">
          <%= f.label :コースの名前, class: "form-list mb-3" %><br><span class="form-list-info ml-2">（16字以内）</span><br>
          <%= f.text_field :place_name, placeholder: "例）〇〇公園", class: "w-100 p-1 mb-5 rounded form" %>
        </div>

        <div class="m-3">
          <%= f.label :コースの画像, class: "form-list mb-3" %><br>
          <%= f.file_field :place_image, id: "preview", class: "w-100 p-1 rounded" %>
        </div>

        <img src=<%= @tweet.place_image %> class = "before_image">
        <div id="image-list"></div>

        <div class="m-3 mt-5">
          <%= f.label :コースの住所, class: "form-list mb-3" %><br><span class="form-list-info ml-2">（30字以内）</span><br>
          <%= f.text_field :address, placeholder: "例）〇〇県〇〇市〇〇区〇〇町１ー１", class: "w-100 p-1 mb-5 rounded form" %>
        </div>

        <div class="m-3">
          <%= f.label :どんな人におすすめ？, class: "form-list mb-3" %><br>
          <div class="text-left ml-3 mt-2">
            <label><%= f.radio_button :level, 1 %>誰でも（これから始める方でも！）</label>
          </div>
          <div class="text-left ml-3 mt-2">
            <label><%= f.radio_button :level, 2 %>経験者（5kmをラクラク走れる方！）</label>
          </div>
        </div>

        <div class="m-3 mt-5">
          <%= f.label :タグ付け, class: "form-list mb-3" %><br><span class="form-list-info ml-2">必須ではありません（１６字以内）</span><br>
          <%= f.text_field :tag_ids, id:'tag_ids', placeholder: "東京,皇居,アップダウン,おしゃれ,観光", class: "w-100 p-1 mb-5 rounded form" %>
        </div>

        <div class="m-3 mt-4">
          <%= f.label :何かひとこと, class: "form-list mb-3" %><br><span class="form-list-info ml-2">（100字以内）</span><br>
          <%= f.text_area :content, placeholder: "例）緑が多くて素敵な公園です", rows: "6", class: "w-100 p-1 mb-5 rounded form" %>
        </div>

        <div>
            <%= f.submit "編集", class: "btn btn-success text-white btn-lg pl-4 pr-4" %>
        </div>
      <% end %>

    </div>
  </div>

</div>

app/views/tweets/index.html.erb
<%# ↓トップページスライド %>
<div class="slide-content row">
  <div class="slide-image">
    <ul class="slider mt-5">
      <li>
        <img src="/images/place_image.png" alt="slick-img">
      </li>
      <li>
        <img src="/images/menu.png" alt="slick-img">
      </li>
      <li>
        <img src="/images/course.png" alt="slick-img">
      </li>
    </ul>
  </div>

  <div class="slide-text">
    <h4>もうランニングで悩まない！</h4><br><br>
    いつも近所でランニング、飽きた！<br>
    大会にエントリーしたけど何していいの？<br>
    ランニングのアプリ使ってるけど、<br>
    ◯kmを◯分かかって、1kmあたり◯秒ペース、<br>
    これってどうなの？<br>
    こんな悩みを持つ方にぴったりのサービスです。<br>
    気になる<strong class="text-dark">ランニングコース</strong>が見つかるかもしれません。<br>
    いつもと違う場所でランニングを楽しみましょう！<br><br>
    また、適切な練習がわからない方、<br>
    まずは<strong class="text-dark">ベストタイムを登録</strong>しましょう。<br>
    <strong class="text-dark">練習メニューや走力レベル</strong>を確認できます。<br><br>
  </div>
</div>
<%# ↑トップページスライド %>

<div class="slide-border"></div>

<%# ↓検索エリア %>
<div class="d-flex justify-content-center">
  <div class="search-group">
    <%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |f| %>
      <div class="d-flex align-items-center justify-content-center w-100">
          <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input p-2 ml-4" %>
          <button type="submit" class="search-btn link"><i class="fas fa-search"></i></button>
      </div>
    <% end %>

    <div class="row mt-4">
      <% @tag_lists.each do |tag| %>
          <%= link_to tag_tweets_path(tag_id: tag.id) do %>
            <div class="tag link"><%= "＃#{tag.name}" %></div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<%# ↑%>

<% if user_signed_in? %>
  <div class="tweet-btn-group">
    <%= link_to new_tweet_path  do %>
      <button class="btn btn-lg tweet-btn text-white link">ランニングコースを投稿</button>
    <% end %>
  </div>
<% end %>

<%# 投稿一覧 %>
<%= render "render/tweets_main_contents" %>
<%# %>

<% if user_signed_in? %>
  <div class="tweet-btn-group">
    <div class="tweet-btn-group-text">
      ↓あなたも投稿してみよう！
    </div>

    <%= link_to new_tweet_path  do %>
      <button class="btn btn-lg tweet-btn text-white link">ランニングコースを投稿</button>
    <% end %>
  </div>
<% end %>

<div class="fixed-btn-dummy">
  <% unless user_signed_in? %>
    <%= link_to new_user_session_path do %>
      <div class='fixed-btn link'>
        <div class='fixed-btn-text'>かんたんログイン<i class="fa fa-angle-right ml-2" aria-hidden="true"></i></div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/tweets/new.html.erb
<div class="forms-container">

  <div class="titles mb-5">ランニングコースを投稿</div>

  <div class="d-flex justify-content-center">
    <div class="forms-content">

      <%= form_with(model: @tweet, local: true) do |f| %>

        <%= render 'render/error_messages', model: f.object %>

        <div class="m-3">
          <%= f.label :コースの名前, class: "form-list mb-3" %><br><span class="form-list-info ml-2">（16字以内）</span><br>
          <%= f.text_field :place_name, placeholder: "例）〇〇公園", class: "w-100 p-1 mb-5 rounded form" %>
        </div>

        <div class="m-3">
          <%= f.label :コースの画像, class: "form-list mb-3" %><br>
          <%= f.file_field :place_image, id: "preview", class: "w-100 p-1 rounded" %>
        </div>

        <div id="image-list"></div>

        <div class="m-3 mt-5">
          <%= f.label :コースの住所, class: "form-list mb-3" %><br><span class="form-list-info ml-2">（30字以内）</span><br>
          <%= f.text_field :address, placeholder: "例）〇〇県〇〇市〇〇区〇〇町１ー１", class: "w-100 p-1 mb-5 rounded form" %>
        </div>

        <div class="m-3">
          <%= f.label :どんな人におすすめ？, class: "form-list mb-3" %><br>
          <div class="text-left ml-3 mt-2">
            <label><%= f.radio_button :level, 1 %>誰でも（これから始める方でも！）　</label>
          </div>
          <div class="text-left ml-3 mt-2">
            <label><%= f.radio_button :level, 2 %>経験者（5kmをラクラク走れる方！）　</label>
          </div>
        </div>

        <div class="m-3 mt-5">
          <%= f.label :タグ付け, class: "form-list mb-3" %><br><span class="form-list-info ml-2">必須ではありません（１６字以内）</span><br>
          <%= f.text_field :tag_ids, id:'tag_ids', placeholder: "東京,皇居,アップダウン,おしゃれ,観光", class: "w-100 p-1 mb-5 rounded form" %>
        </div>

        <div class="m-3 mt-4">
          <%= f.label :何かひとこと, class: "form-list mb-3" %><br><span class="form-list-info ml-2">（100字以内）</span><br>
          <%= f.text_area :content, placeholder: "例）緑が多くて素敵な公園です。", rows: "6", class: "w-100 p-1 mb-5 rounded form" %>
        </div>

        <div>
            <%= f.submit "投稿", class: "btn btn-success text-white btn-lg pl-4 pr-4" %>
        </div>

      <% end %>

    </div>
  </div>

</div>

app/views/tweets/search.html.erb
<%= render "render/tweets_search"%>

app/views/tweets/show.html.erb
<div class="tweet-show-container f-f-monospace">
  <div class="tweet-show-flex">

    <div>
      <%# ↓メイン（選択したランニングコース）の情報 %>
      <div>
        <img src=<%= @tweet.place_image %> class = "tweet-show-place-image">
      </div>

      <div class="d-flex justify-content-between align-items-end mb-5">
        <div class="tweet-show-place-name">
            <%= @tweet.place_name %>
        </div>
        <div class="level-text mb-2">
          <i class="fas fa-check-square"></i>
          <% if @tweet.level == 1 %>
            <strong>初心者</strong>
          <% else @tweet.level == 2 %>
            <strong>経験者</strong>
          <% end %>
            におすすめ！
        </div>
      </div>

      <div class="tweet-show-place-info mb-3">
        <div class="d-flex align-items-end user-group">
          <div>
            <span class="like-<%= @tweet.id %>">
              <%= render partial: "render/like", locals: { tweet: @tweet } %>
            </span>
            <i class="fas fa-clock ml-2"></i><%= "#{time_ago_in_words(@tweet.created_at)}前" %>
            <%= @tweet.created_at.to_s(:datetime_jp) %>
          </div>
          <%= link_to @tweet.user, class: "link" do %>
            <div class="d-flex align-items-end tweet-show-profile">
              <div class="tweet-show-image">
                <% if @tweet.user.image.present? %>
                  <img src=<%= @tweet.user.image %> class = "tweet-show-image-icon">
                <% else %>
                    <img src="/images/dog2.png" class = "tweet-show-image-icon">
                <% end %>
              </div>
              <div class="tweet-user">
                <%= @tweet.user.nickname %>
              </div>
            </div>
          <% end %>
        </div>

        <div class="d-flex tweet-show-btns">
          <% if current_user&.id == @tweet.user_id %>
            <div class="">
              <%= link_to edit_tweet_path(@tweet.id) do %>
                <button type="button" class="tweet-show-btn btn btn-success text-white">編集</button>
              <% end %>
            </div>

            <div class="tweet-show-delete-btn">
              <%= link_to @tweet, method: :delete do %>
                <button type="button" class="tweet-show-btn btn bg-dark text-white">削除</button>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row show-tag">
        <% @tweet_tags.each do |tag| %>
            <%= link_to tag_tweets_path(tag_id: tag.id) do %>
              <div class="tag link"><%= "＃#{tag.name}" %></div>
            <% end %>
        <% end %>
      </div>

      <div class="parent">
        <div class="tweet-show-place-texts">
          <%= @tweet.content %>
        </div>
      </div>
      <%# ↑メイン（選択したランニングコース）の情報 %>

      <%# ↓コメント関係 %>
      <div class="message-container">
        <div class="titles mb-1">コメント一覧</div>
        <br>

        <% if user_signed_in? %>
          <%= form_with url: tweet_messages_path(@tweet.id) do |f| %>
            <div class="massage-form-group d-flex align-items-center">
              <div>
                <%= f.text_area :text, placeholder: "コメントを入力", class: "massage-form p-2 mt-1 rounded" %>
              </div>
              <div class="record-item">
                <%= f.submit "コメント", class: "record-item btn btn-success text-white mt-3" %>
              </div>
            </div>
          <% end %>
        <% end %>

        <% unless @tweet_messages.present? %>
          <div class="message mt-4">
            この投稿へのコメントはありません
          </div>
        <% end %>

        <div id='messages'>
          <% @tweet_messages.each do |message| %>
            <div class="message mt-3">
              <%= message.text.truncate(100) %>
              <br>

              <div class="mt-2">
                <span class="post-time-message"><%= message.created_at.to_s(:datetime_jp) %></span>
                <% if message.user == current_user %>
                    <%= link_to "あなた", message.user, class: "link message-user" %>
                <% else %>
                    <%= link_to message.user.nickname, message.user, class: "link message-user" %>
                    <span class="message-user-san"></span>さん
                <% end %>
              </div>

            </div>
          <% end %>
        </div>
      </div>
      <%# ↑コメント関係 %>

      <br><br><br>

      <%# 住所・地図 %>
      <div class="address">
        <strong>　　住所 ：　</strong><%= @tweet.address %>
      <div id='map' class="map"></div>
      <%#  %>

      </div>
    </div>

    <%# ↓関連コース（実際はランダムに7つ表示） %>
    <div class="mini-contents">
      <h4 class="randam-title">他のコース</h4>

      <div class="randam-tweet">
        <% @random.each do |tweet| %>
          <div class="mini-group">
            <div class="mini-place-image">
              <%= link_to tweet, class: "link" do %>
                <img src=<%= tweet.place_image %> class = "mini-place-image-icon">
              <% end %>
            </div>
            <div class="mini-place-name">
              <strong><%= tweet.place_name.truncate(15) %></strong>
            </div>
            <div class="mini-address">
              <%= tweet.address.truncate(15) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%# ↑関連コース %>

  </div>
</div>


<script type="text/javascript">
    function initMap() {

        // 緯度・経度取得
        const test ={ lat: <%= @tweet.latitude %>, lng: <%= @tweet.longitude %> };
        const map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: test
        });
        const transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        const contentString = '住所：<%= @tweet.address %>';
        const infowindow = new google.maps.InfoWindow({
              content: contentString
        });

        const marker = new google.maps.Marker({
              position:test,
              map: map,
              title: contentString
        });

        marker.addListener('click', function() {
            infowindow.open(map, marker);
        });
    }
</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>

app/views/tweets/tag_search.html.erb
<%= render "render/tweets_search"%>