config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  root 'tweets#index'
  resources :tweets do
    collection do
      get 'search'
    end
    resources :messages, only: :create
  end

  resources :tags do
    get 'tweets', to: 'tweets#tag_search'
  end

  resources :users, only: :show do
    resources :five_km_records,  only: [:create, :update, :destroy]
    resources :ten_km_records,  only: [:create, :update, :destroy]
    resources :half_records,  only: [:create, :update, :destroy]
    resources :full_records,  only: [:create, :update, :destroy]
    resources :vdots,  only: [:index]
  end

  resources :follow_relationships, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
  resources :records,  only: [:new, :edit]
  resources :vdots,  only: [:index]
  post '/tweets/:tweet_id/likes' => 'likes#create'
  delete '/tweets/:tweet_id/likes' => 'likes#destroy'
  mount ActionCable.server => '/cable'
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  # ----- アソシエーション -----------------------------------
    belongs_to :visitor, class_name: 'User', optional: true
    belongs_to :visited, class_name: 'User', optional: true
    belongs_to :tweet, optional: true
    belongs_to :message, optional: true


  # ----- バリデーション ------------------------------------
    validates :visitor_id, presence: true
    validates :visited_id, presence: true
    ACTION_VALUES = ['like', 'follow', 'message']
    validates :action, presence: true, inclusion: { in: ACTION_VALUES }
    validates :checked, inclusion: { in: [true, false] }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    # ログイン者の通知を表示
    @notifications = current_user.passive_notifications.includes([:visitor])
  end

  def destroy
    # ログイン者の通知を全て削除
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_form(notification)
    # 通知を送ってきたユーザーを取得
    @visitor = notification.visitor
    # #コメントの内容を通知に表示する
    @message = nil
    @visitor_message = notification.message_id
    # notification.actionがfollowかlikeかcommentかで処理を変える
    case notification.action
    when 'follow'
      # aタグで通知を作成したユーザーshowのリンクを作成
      tag.a(notification.visitor.nickname, href: user_path(@visitor)) + 'があなたをフォローしました'
    when 'like'
      tag.a(notification.visitor.nickname, href: user_path(@visitor)) + 'が' + tag.a('あなたの投稿', href: tweet_path(notification.tweet_id)) + 'にいいねしました'
    when 'message'
      # コメントの内容と投稿のタイトルを取得
      @message = Message.find_by(id: @visitor_message)
      tag.a(@visitor.nickname, href: user_path(@visitor)) + 'が' + tag.a('あなたの投稿', href: tweet_path(notification.tweet_id)) + 'にコメントしました'
    end
  end
end

app/views/notifications/_notification.html.erb
<div class="notification-view">
  <div class="notification-content">
    <div class="text-dark">
      <%= notification_form(notification) %>
    </div>

    <% if !@message.nil? %>
    <div class="text-center mt-2">
      <%# コメントの内容（最大25文字） %>
      <span class="notification-comment ml-3 text-secondary"><%= @message.text.truncate(25) %></span>
    </div>
    <% end %>
    <div class="moderate-font text-right">
      <%# 通知の作成時間 %>
      <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
    </div>
  </div>
</div>

app/views/notifications/index.html.erb
<div class="forms-container">

  <div class="titles">お知らせ</div>
  <div class="notification-contents">
    <%# 通知が表示されていれば、「確認済みにする」ボタンを表示 %>
    <% if @notifications.exists? %>
      <div class="text-right mb-5">
          <%= link_to notification_path(@notifications), method: :delete, class: "link text-warning" do %>
            <i class="fas fa-trash mr-1"></i>確認済みにする
          <% end %>
      </div>
      <div class="notification-index">
          <%# 通知の繰り返し表示 %>
          <%= render @notifications %>
      </div>
    <% else %>
        <p class="mt-5">お知らせはありません</p>
    <% end %>
  </div>

</div>