config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  root 'tweets#index'
  resources :tweets do
    collection do
      get 'search'
    end
    resources :messages, only: :create
  end

  resources :tags do
    get 'tweets', to: 'tweets#tag_search'
  end

  resources :users, only: :show do
    resources :five_km_records,  only: [:create, :update, :destroy]
    resources :ten_km_records,  only: [:create, :update, :destroy]
    resources :half_records,  only: [:create, :update, :destroy]
    resources :full_records,  only: [:create, :update, :destroy]
    resources :vdots,  only: [:index]
  end

  resources :follow_relationships, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
  resources :records,  only: [:new, :edit]
  resources :vdots,  only: [:index]
  post '/tweets/:tweet_id/likes' => 'likes#create'
  delete '/tweets/:tweet_id/likes' => 'likes#destroy'
  mount ActionCable.server => '/cable'
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # 未ログイン者の制限
  before_action :authenticate_user!

  def new
  end

  def edit
    user = User.find(params[:id])
    redirect_to user_path(current_user.id), notice: '自分以外のベストタイムは編集できません' if current_user.id != user.id

    # ログイン者の各ベストタイムを取得（存在すれば）
    get_record
  end

  private

  # ログイン者の各ベストタイムを取得（存在すれば）
  def get_record
    @five_record = FiveKmRecord.find_by(user_id: current_user.id) if FiveKmRecord.where(user_id: current_user.id).present?
    @ten_record = TenKmRecord.find_by(user_id: current_user.id) if TenKmRecord.where(user_id: current_user.id).present?
    @half_record = HalfRecord.find_by(user_id: current_user.id) if HalfRecord.where(user_id: current_user.id).present?
    @full_record = FullRecord.find_by(user_id: current_user.id) if FullRecord.where(user_id: current_user.id).present?
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/edit.html.erb
<div class="forms-container">

  <% if FiveKmRecord.where(user_id:current_user.id).present? %>
    <%= form_with url: user_five_km_record_path(current_user), method: :put, local: true do |f| %>
      <div class="record-title mt-0">5kmのベストタイム</div>
      <div class="record-content">
        <div class="record-items text-dark mt-3">
          <div class="record-item">
            <%= f.collection_select(:minute_id, Minute.all, :id, :name, {selected: @five_record.minute_id }, class: "p-2") %>：分
          </div>
          <div class="record-item">
            <%= f.collection_select(:second_id, Second.all, :id, :name, {selected: @five_record.second_id }, class: "p-2") %>：秒
          </div>
        </div>

        <div class="d-flex">
          <div class="record-item mt-3 ml-3">
            <%= f.submit "編集", class: "btn btn-success text-white nav-link" %>
          </div>
          <div class="record-item  mt-3">
            <%= link_to  user_five_km_record_path(current_user), method: :delete do %>
              <button type="button" class="btn text-white nav-link btn-secondary user-show-delete-btn link">削除</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="forms-border"></div>
  <% end %>

  <% if TenKmRecord.where(user_id:current_user.id).present? %>
    <%= form_with url: user_ten_km_record_path(current_user), method: :put, local: true do |f| %>
      <div class="record-title">10kmのベストタイム</div>
      <div class="record-content">
        <div class="record-items text-dark mt-3">
          <div class="record-item">
            <%= f.collection_select(:minute_id, Minute.all, :id, :name, {selected: @ten_record.minute_id }, class: "p-2") %>：分
          </div>
          <div class="record-item">
            <%= f.collection_select(:second_id, Second.all, :id, :name, {selected: @ten_record.second_id }, class: "p-2") %>：秒
          </div>
        </div>

        <div class="d-flex">
          <div class="record-item mt-3 ml-3">
            <%= f.submit "編集", class: "btn btn-success text-white nav-link" %>
          </div>
          <div class="record-item mt-3">
            <%= link_to  user_ten_km_record_path(current_user), method: :delete do %>
              <button type="button" class="btn text-white nav-link btn-secondary user-show-delete-btn link">削除</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="forms-border"></div>
  <% end %>

  <% if HalfRecord.where(user_id:current_user.id).present? %>
    <%= form_with url: user_half_record_path(current_user), method: :put, local: true do |f| %>
      <div class="record-title">ハーフのベストタイム</div>
      <div class="record-content">
        <div class="record-items text-dark mt-3">
          <div class="record-item">
            <%= f.collection_select(:hour_id, Hour.all, :id, :name, {selected: @half_record.hour_id }, class: "p-2") %>　: 時間
          </div>
          <div class="record-item">
            <%= f.collection_select(:minute_id, Minute.where(id:[*0..59]), :id, :name, {selected: @half_record.minute_id }, class: "p-2") %>：分
          </div>
          <div class="record-item">
            <%= f.collection_select(:second_id, Second.all, :id, :name, {selected: @half_record.second_id }, class: "p-2") %>：秒
          </div>
        </div>

        <div class="d-flex">
          <div class="record-item mt-3 ml-3">
            <%= f.submit "編集", class: "btn btn-success text-white nav-link" %>
          </div>
          <div class="record-item mt-3">
            <%= link_to  user_half_record_path(current_user), method: :delete do %>
              <button type="button" class="btn text-white nav-link btn-secondary user-show-delete-btn link">削除</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="forms-border"></div>
  <% end %>

  <% if FullRecord.where(user_id:current_user.id).present? %>
    <%= form_with url: user_full_record_path(current_user), method: :put, local: true do |f| %>
      <div class="titles record-title">フルのベストタイム</div>
      <div class="record-content">
        <div class="record-items text-dark mt-3">
          <div class="record-item">
            <%= f.collection_select(:hour_id, Hour.all, :id, :name, {selected: @full_record.hour_id }, class: "p-2") %>　: 時間
          </div>
          <div class="record-item">
            <%= f.collection_select(:minute_id, Minute.where(id:[*0..59]), :id, :name, {selected: @full_record.minute_id }, class: "p-2") %>：分
          </div>
          <div class="record-item">
            <%= f.collection_select(:second_id, Second.all, :id, :name, {selected: @full_record.second_id }, class: "p-2") %>：秒
          </div>
        </div>

        <div class="d-flex">
          <div class="record-item mt-3">
            <%= f.submit "編集", class: "btn btn-success text-white nav-link" %>
          </div>
          <div class="record-item mt-3">
            <%= link_to  user_full_record_path(current_user), method: :delete do %>
              <button type="button" class="btn text-white nav-link btn-secondary user-show-delete-btn link">削除</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <%# 登録されているベストタイムが全くなければ表示 %>
  <% unless FiveKmRecord.where(user_id:current_user.id).present? ||
        TenKmRecord.where(user_id:current_user.id).present?  ||
        HalfRecord.where(user_id:current_user.id).present?   ||
        FullRecord.where(user_id:current_user.id).present? %>
    <div class="text-center">
        <div class="record-hide-text text-dark pb-5">ベストタイムを登録しましょう！</div>
        <%= link_to new_record_path do %>
          <button type="button" class="btn btn-success btn-lg mt-4">登録ページへ<i class="fa fa-angle-right ml-2" aria-hidden="true"></i></button>
        <% end %>
        <br>
        <%= link_to user_path(current_user), class: "text-success" do %>
          <div class="mt-5 user-link-to-edit">
            マイページへ<i class="fa fa-angle-right ml-2" aria-hidden="true"></i>
          </div>
        <% end %>
    </div>
  <% end %>
  <%#  %>

</div>

app/views/records/new.html.erb
<div class="forms-container">

  <% unless FiveKmRecord.where(user_id:current_user.id).present? %>
    <%= form_with url: user_five_km_records_path(current_user), local: true do |f| %>
      <div class="record-title mt-0">5kmのベストタイム</div>
      <div class="record-content">
        <div class="record-items text-dark mt-3">
          <div class="record-item">
            <%= f.collection_select(:minute_id, Minute.all, :id, :name, {}, class: "p-2") %>：分
          </div>
          <div class="record-item">
            <%= f.collection_select(:second_id, Second.all, :id, :name, {}, class: "p-2") %>：秒
          </div>
        </div>
        <div class="mt-1 ml-3">
          <%= f.submit "登録", class: "record-btn btn btn-success text-white" %>
        </div>
      </div>
    <% end %>
    <div class="forms-border"></div>
  <% end %>

  <% unless TenKmRecord.where(user_id:current_user.id).present? %>
    <%= form_with url: user_ten_km_records_path(current_user), local: true do |f| %>
      <div class="record-title">10kmのベストタイム</div>
      <div class="record-content">
        <div class="record-items text-dark mt-3">
          <div class="record-item">
            <%= f.collection_select(:minute_id, Minute.all, :id, :name, {}, class: "p-2") %>：分
          </div>
          <div class="record-item">
            <%= f.collection_select(:second_id, Second.all, :id, :name, {}, class: "p-2") %>：秒
          </div>
        </div>

        <div class="mt-1 ml-3">
          <%= f.submit "登録", class: "record-btn btn btn-success text-white" %>
        </div>
      </div>
    <% end %>
     <div class="forms-border"></div>
  <% end %>

  <% unless HalfRecord.where(user_id:current_user.id).present? %>
    <%= form_with url: user_half_records_path(current_user), local: true do |f| %>
      <div class="record-title">ハーフのベストタイム</div>
      <div class="record-content">
        <div class="record-items text-dark mt-3">
          <div class="record-item">
            <%= f.collection_select(:hour_id, Hour.all, :id, :name, {}, class: "p-2") %>　: 時間
          </div>
          <div class="record-item">
            <%= f.collection_select(:minute_id, Minute.where(id:[*0..59]), :id, :name, {}, class: "p-2") %>：分
          </div>
          <div class="record-item">
            <%= f.collection_select(:second_id, Second.all, :id, :name, {}, class: "p-2") %>：秒
          </div>
        </div>

        <div class="mt-1 ml-3">
          <%= f.submit "登録", class: "record-btn btn btn-success text-white" %>
        </div>
      </div>
    <% end %>
    <div class="forms-border"></div>
  <% end %>

  <% unless FullRecord.where(user_id:current_user.id).present? %>
    <%= form_with url: user_full_records_path(current_user), local: true do |f| %>
      <div class="record-title">フルのベストタイム</div>
      <div class="record-content">
        <div class="record-items text-dark mt-3">
          <div class="record-item">
            <%= f.collection_select(:hour_id, Hour.all, :id, :name, {}, class: "p-2") %>　: 時間
          </div>
          <div class="record-item">
            <%= f.collection_select(:minute_id, Minute.where(id:[*0..59]), :id, :name, {}, class: "p-2") %>：分
          </div>
          <div class="record-item">
            <%= f.collection_select(:second_id, Second.all, :id, :name, {}, class: "p-2") %>：秒
          </div>
        </div>

        <div class="mt-1 ml-3">
          <%= f.submit "登録", class: "record-btn btn btn-success text-white" %>
        </div>
      </div>
    <% end %>
  <% end %>

  <%# 全てのベストタイム登録されていれば表示 %>
  <% if FiveKmRecord.where(user_id:current_user.id).present? &&
        TenKmRecord.where(user_id:current_user.id).present?  &&
        HalfRecord.where(user_id:current_user.id).present?   &&
        FullRecord.where(user_id:current_user.id).present? %>
    <div class="text-center">
        <div class="record-hide-text text-dark pb-5">全てのベストタイムを登録済みです！</div>
        <%= link_to user_path(current_user) do %>
          <button type="button" class="btn btn-success btn-lg mt-4">マイページへ<i class="fa fa-angle-right ml-2" aria-hidden="true"></i></button>
        <% end %>
        <br>
        <%= link_to edit_record_path(current_user), class: "text-success" do %>
          <div class="mt-5 user-link-to-edit">
            ベストタイム編集ページへ<i class="fa fa-edit ml-1" aria-hidden="true"></i>
          </div>
        <% end %>
    </div>
  <% end %>

</div>