config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  root 'tweets#index'
  resources :tweets do
    collection do
      get 'search'
    end
    resources :messages, only: :create
  end

  resources :tags do
    get 'tweets', to: 'tweets#tag_search'
  end

  resources :users, only: :show do
    resources :five_km_records,  only: [:create, :update, :destroy]
    resources :ten_km_records,  only: [:create, :update, :destroy]
    resources :half_records,  only: [:create, :update, :destroy]
    resources :full_records,  only: [:create, :update, :destroy]
    resources :vdots,  only: [:index]
  end

  resources :follow_relationships, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
  resources :records,  only: [:new, :edit]
  resources :vdots,  only: [:index]
  post '/tweets/:tweet_id/likes' => 'likes#create'
  delete '/tweets/:tweet_id/likes' => 'likes#destroy'
  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>

    <title>Run Record</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# 走力グラフ用 %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js" type="text/javascript"></script>

    <%# jQuery呼び出し %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>

    <%# トップページスライド用 %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  </head>

  <body>

   <%# フラッシュメッセージ %>
   <%= render 'render/notifications' %>

    <%# ↓ヘッダーナビ %>
    <nav class="nav-parent navbar navbar-expand-md navbar-dark fixed-top w-100">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top nav-items">
        <%= link_to root_path do %>
          <button type="button" class="btn top-btn btn-lg nav-link link">Run Record</button>
        <% end %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">

            <% if user_signed_in? %>
              <%# ヘッダーナビボタン（ログイン時） %>
              <li class="nav-item header-item link">
                <%= link_to "お知らせ", notifications_path, class: "text-white nav-link header-nav-link" %>
              </li>
              <li class="nav-item header-item link">
                <%= link_to "#{current_user.nickname}", user_path(current_user.id), class: "text-white nav-link header-nav-link" %>
              </li>
              <li class="nav-item header-item link">
                <%= link_to "走力一覧", user_vdots_path(current_user), class: "text-white nav-link header-nav-link" %>
              </li>
              <li class="nav-item header-item link">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white nav-link header-nav-link" %>
              </li>
            <% else %>
              <%# ヘッダーナビボタン（未ログイン時） %>
              <li class="nav-item header-item link">
                <%= link_to "走力一覧", vdots_path, class: "text-white nav-link header-nav-link" %>
              </li>
              <li class="nav-item header-item link">
                <%= link_to "かんたんログイン", new_user_session_path, class: "text-white nav-link header-nav-link" %>
              </li>
              <li class="nav-item header-item link">
                <%= link_to "ログイン", new_user_session_path, class: "text-white nav-link header-nav-link" %>
              </li>
              <li class="nav-item header-item link">
                <%= link_to "新規登録",new_user_registration_path, class: "text-white nav-link header-nav-link" %>
              </li>
            <% end %>

          </ul>
        </div>
      </nav>
    <%# ↑ヘッダーナビ %>
    </nav>
    <div class="d-flex justify-content-center">
      <%# 最大widthを1300px、最低の高さを計100vhになるように %>
      <div class="max" >

        <%= yield %>

      </div>
    </div>
    <footer class="footer d-flex justify-content-center align-items-end">
      <div>© 2020 Run Record</div>
    </footer>

    <script>
      $(function(){
        // リンクにマウスオーバーで色を変える
        $(".link").mouseover(function () {
          $(this).css("opacity", "0.7");
        });
        $(".link").mouseout(function () {
          $(this).css("opacity", "1");
        });

        // トップページのスライドの流れるスピード
        $('.slider').slick({
          dots: true,
          autoplay: true,
          autoplaySpeed: 3000,
          arrows: false
        });
      });

    </script>

  </body>
</html>